### ISSUE TITLE
✨대출 페이지 제작(아이)

### ISSUE THREAD

**Issue by NOEL-code** [ii-sol/frontend#5]
## 📌 Description
- 

## 📝 To-do
- [ ] 채권자 선택
- [ ] 대출 금액 선택
- [ ] 대출 기간 선택
- [ ] 대출 메세지 선택
- [ ] 대출 신청 완료 페이지
- [ ] 대출 상세 페이지
- [ ] 대출 내역 조회
- [ ] 대출 메인 페이지
